[package]
name = "zmodem2-bin"
version = "0.1.4"
edition = "2021"

[dependencies]
anyhow = "1.0"
argh = "0.1"
indicatif = "0.17"
zmodem2 = { path = "../zmodem2" }

[[bin]]
name = "rzm"
path = "src/bin/rzm.rs"

[[bin]]
name = "szm"
path = "src/bin/szm.rs"

[[test]]
name = "integration"
path = "tests/integration.rs"
harness = true

[features]
integration_test = []
