[package]
authors = ["jarkkojs", "aarbuzov"]
name = "zmodem2-bin"
description = "ZMODEM file transfer protocol"
repository = "https://codeberg.org/jarkko/zmodem2.git"
license = "MIT OR Apache-2.0"
version = "0.2.0"
edition = "2021"
rust-version = "1.73"

[dependencies]
anyhow = "1.0"
argh = "0.1"
indicatif = "0.17"
zmodem2 = { path = "../zmodem2", version = "0.2.0" }

[[bin]]
name = "rzm"
path = "src/bin/rzm.rs"

[[bin]]
name = "szm"
path = "src/bin/szm.rs"

[dev-dependencies]
env_logger = "0.10"
log = "0.4"

[[test]]
name = "integration"
path = "tests/integration.rs"
harness = true
