[package]
authors = ["jarkkojs", "aarbuzov"]
name = "zmodem2"
description = "ZMODEM file transfer protocol"
repository = "https://codeberg.org/jarkko/zmodem2.git"
license = "MIT OR Apache-2.0"
version = "0.3.0"
edition = "2021"
rust-version = "1.78"

[features]
default = ["std"]
std = []

[dependencies]
bitflags = "2.4"
heapless = "0.8"
log = { version = "0.4", default-features = false }
strum = { version = "0.27", default-features=false, features = ["derive"] }
strum_macros = { version = "0.27", default-features=false }

[dev-dependencies]
rstest = "0.25"

[[test]]
name = "protocol"
path = "tests/protocol.rs"
harness = true
